# Generated by Django 3.2.13 on 2022-07-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220622_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Mobile No'),
        ),
    ]
