# Generated by Django 3.2.13 on 2022-07-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=15, verbose_name='Total Price'),
        ),
    ]
