# Generated by Django 3.2.13 on 2022-07-13 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20220712_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='last_login',
            new_name='last_accessed',
        ),
    ]
