# Generated by Django 3.2.13 on 2022-07-17 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_patient_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorAvailability',
        ),
    ]
