# Generated by Django 3.2.13 on 2022-07-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='present',
            field=models.BooleanField(default=False, verbose_name='Present'),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
