# Generated by Django 3.2.13 on 2022-07-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensary', '0002_auto_20220730_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Bill Date'),
        ),
    ]
