# Generated by Django 3.2.13 on 2022-07-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensary', '0004_auto_20220730_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_mode',
            field=models.CharField(choices=[('credit_card', 'credit card'), ('debit_card', 'debit card'), ('upi', 'upi'), ('net_banking', 'net banking'), ('cash', 'cash')], default='cash', max_length=11),
            preserve_default=False,
        ),
    ]
