# Generated by Django 3.2.13 on 2022-08-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensary', '0005_transaction_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Discount (%)'),
            preserve_default=False,
        ),
    ]
