# Generated by Django 3.2.13 on 2022-07-17 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoravailability',
            old_name='not_present',
            new_name='not_available',
        ),
    ]
