# Generated by Django 3.2.13 on 2022-07-29 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_mobile'),
        ('registration', '0008_appointment_diagnosed'),
        ('doctor', '0002_rename_not_present_doctoravailability_not_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(verbose_name='Diagnosis')),
                ('symptoms', models.TextField(verbose_name='Symptoms')),
                ('medicine', models.JSONField()),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='registration.appointment')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hospital')),
            ],
        ),
    ]
