# Generated by Django 3.2.13 on 2022-07-31 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_fees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fees',
        ),
    ]
